### ISSUE TITLE
Federation: Social Sharing buttons

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/socialsharing#15]
<img width="972" alt="bildschirmfoto 2017-05-05 um 10 49 06" src="https://cloud.githubusercontent.com/assets/19711361/25739100/a84d144c-3180-11e7-871d-30e7c5f45b44.png">
The Facebook, Twitter, Google+ and Diaspora icons are shown, also if you don't have those social sharing plugins enabled. Can we change this? @schiessle

**Comment by marcelklehr** [comment]
This has nothing to do with this app.
