### ISSUE TITLE
Facebook sharing

### ISSUE THREAD

**Issue by Leftspace21** [nextcloud/socialsharing#19]
I shared a picture to Facebook from my Nextcloud 12 instance. This worked perfectly, but the title image for any image is always “our website is at www.**** a place to organise”. This is the content we have put on the login page pointing to our public website.

Is there an easy way either to remove this default text or better still - make the image name show instead - or perhaps the option to add custom text
![share-facebook](https://user-images.githubusercontent.com/11635256/28522124-ad72b2e2-706e-11e7-8a5c-c47c2b0a48af.PNG)
![whats_shown](https://user-images.githubusercontent.com/11635256/28522125-ad743626-706e-11e7-9e0e-48df7c34ae4e.PNG)

**Comment by juliushaertl** [comment]
The title is set by the og:title in the files_sharing app, so this is out of scope for the socialsharing_facebook. I think we have improved there in the latest versions of Nextcloud, so please try that with a newer version.
