### ISSUE TITLE
Reconsider app name and a nice icon

### ISSUE THREAD

**Issue by schiessle** [nextcloud/socialsharing#2]
I think it is great to have a dedicated app for the "share on social networks" buttons. But the app name sounds a bit clumsy. I don't care about the technical name but in the apps menu we also call it "Social sharing default" at the moment. What does "default" means here? Also overall it isn't obvious for what the app stands for.

How about calling it "Social networks buttons" instead? Or even better "Share on social networks"?

And while we are on it... Maybe someone can create a nice app icon? Maybe a assembly of the social network icons from the img dir?

Opinions?

cc @rullzer @jancborchardt @nextcloud/designers

**Comment by MorrisJobke** [comment]
"Sharing to social networks"?

**Comment by jancborchardt** [comment]
I seriously have to ask why this is a separate app. Why do we make pretty normal simple core functionality like this and also the quota warnings apps? This just clutters up the list of apps with what is basically system settings. That’s not cool and we should stop doing that.

This belongs in the sharing settings as »Enable social sharing buttons for link«, nothing more.

**Comment by rullzer** [comment]
@jancborchardt no I won't do that. Because there are a gazillion social networks out there and I'm not comfortable with deciding what has to be in it. And I also don't believe such code should be in the server part the managing part has to. And then an admin just enables the social sharing apps they want.

**Comment by rullzer** [comment]
@schiessle as discussed yesterday. This was just an example app that I needed (with more than 1 to test the server code). Plan is to have 1 app per button. So then the name will also be better ;)

**Comment by raimund-schluessler** [comment]
Couldn't the most common networks be included in core and others be provided as apps?

**Comment by rullzer** [comment]
No, because we then get into the discussion of what is common and what not.

**Comment by rullzer** [comment]
Splitup fixed with https://github.com/nextcloud/socialsharing/pull/4
So now they are called a bit more proper ;)

**Comment by jancborchardt** [comment]
> Plan is to have 1 app per button.

This is just not properly usable. This is just adding too many settings by veiling them as apps. I don’t think this is ok and this is not how we do design at Nextcloud. cc @karlitschek @jospoortvliet 

> No, because we then get into the discussion of what is common and what not.

We can just have a user number cutoff. Right now, Facebook, Twitter, Google+ are the obvious choices.

**Comment by MariusBluem** [comment]
> Right now, Facebook, Twitter, Google+ are the obvious choices.

I've already written something about that here: https://github.com/nextcloud/server/pull/3679#issuecomment-284538887 ... common networks should not be splitted up into several apps 😒

**Comment by rullzer** [comment]
@jancborchardt that is just not true. Then we get into should instagram be there. Or the chinese twitter variant (which has a shitload of users) etc. Anyway I won't add it to core. We have way to much stuff there already. Plus this is exactly why we have apps.

If anybody wants to maintain an app that bundles what they think are the most logical choices be my guest. But I won't.

**Comment by jancborchardt** [comment]
@rullzer this is not about »why we have apps«, it’s about the default Nextcloud experience. And if people have to install an app to be able to do something as basic as sharing a file to another platform which is widely used then that’s not usable. Also, just saying, another certain project doesn’t make this a big installable necessity.

**Comment by MorrisJobke** [comment]
@jancborchardt The current problem is: This is basically done now and there are more urgent things to do than to implement the admin interface for this tiny thing here. If somebody wants to pick up on making this completely in the admin panel only - feel free to do it, but this tiny thing here is done for now. When we have time we can address the installation/configuration problem here.
