### ISSUE TITLE
social sharing not work after update to 14

### ISSUE THREAD

**Issue by CNBroderick** [nextcloud/socialsharing#26]
I have successfully installed them.
![app installed](https://user-images.githubusercontent.com/27131135/45497828-49306880-b7ab-11e8-9b81-0708775f9a9b.jpg)

But after I upgraded to version 14, these buttons are gone.
There is no place to get a direct share connection. Just like the one shown in the store below.
![raw](https://user-images.githubusercontent.com/27131135/45497829-49c8ff00-b7ab-11e8-8262-bf5ee403dbf7.jpg)

Can you help me or how can it solve it? Thanks~

**Comment by juliushaertl** [comment]
Please try to upgrade to 1.0.4, since 1.0.3 was only supporting Nextcloud 13.
