### ISSUE TITLE
socialsharing_email not compatible with NC 15?

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/socialsharing#27]
NC 15 updater tells me "Social sharing via email" is not ready yet.

**Comment by schiessle** [comment]
@rullzer can you have a look? Seems that all social sharing apps are not yet released for 15. Thanks!

**Comment by stratege1401** [comment]
Dirty Santa killed the update ...

**Comment by hno** [comment]
If you have it installed but can't activate then you can try manually bumping max-version in custom_apps/<appname>/appinfo/info.xml to see if that brings the app alive. The app obviously needs testing for compatibility with nc 15.

**Comment by e-alfred** [comment]
@rullzer Any news on updating these apps? They are marked "official", so it would be good to have them compatible with Nextcloud 15.

**Comment by rullzer** [comment]
submitted. coming to an appstore near you in the next hour

**Comment by stondino00** [comment]
Does this work in nextcloud 15.0.4?  I'm running the ubuntu nextcloud snap instance and this app does nothing when I click on the public link options, then "share to email" nothing happens.
