### ISSUE TITLE
socialsharing_email 1.0.5 kills public sharing by link 

### ISSUE THREAD

**Issue by herrmannsdorfer** [nextcloud/socialsharing#29]
Roeland,

your fix #27 killed the "Share link" option for creating a public link. Disabling your app restores the function.

![share_link](https://user-images.githubusercontent.com/43957716/50836490-9d161d00-1359-11e9-9e94-7ca8f0c4b9ce.png)

**Comment by kchan101** [comment]
It also stops any existing shares from being listed so that they can't be deleted/updated etc

**Comment by violoncelloCH** [comment]
this is the according error in the browser console:
`ReferenceError: link is not defined sharedialoglinkshareview.js:585:5`
<details>

```
render/<
https://ncdev/core/js/sharedialoglinkshareview.js:585:5
m.forEach
https://ncdev/core/vendor/underscore/underscore-min.js:5:2350
addMethod/<
https://ncdev/core/vendor/backbone/backbone.js:87:25
render
https://ncdev/core/js/sharedialoglinkshareview.js:583:4
render
https://ncdev/core/js/sharedialogview.js:785:4
initialize/<
https://ncdev/core/js/sharedialogview.js:82:5
triggerEvents
https://ncdev/core/vendor/backbone/backbone.js:371:32
triggerApi
https://ncdev/core/vendor/backbone/backbone.js:356:19
eventsApi
https://ncdev/core/vendor/backbone/backbone.js:155:16
Events.trigger
https://ncdev/core/vendor/backbone/backbone.js:346:5
set
https://ncdev/core/vendor/backbone/backbone.js:515:11
fetch/<
https://ncdev/core/js/shareitemmodel.js:739:5
j
https://ncdev/core/vendor/jquery/dist/jquery.min.js:2:26920
fireWith
https://ncdev/core/vendor/jquery/dist/jquery.min.js:2:27738
h/<
https://ncdev/core/vendor/jquery/dist/jquery.min.js:2:29050
j
https://ncdev/core/vendor/jquery/dist/jquery.min.js:2:26920
fireWith
https://ncdev/core/vendor/jquery/dist/jquery.min.js:2:27738
x
https://ncdev/core/vendor/jquery/dist/jquery.min.js:4:11251
b/<
https://ncdev/core/vendor/jquery/dist/jquery.min.js:4:14765
```

</details>

**Comment by e-alfred** [comment]
Can confirm, disabling the Social Sharing app fixes the missing "Share link" button.

**Comment by LsPjvVzszDt** [comment]
I found that I could also have Chrome not display the share icon.

For both browsers disabling the ad-blocker resolved the issue.

**Comment by Huster-at-github** [comment]
Yes: Disabling UBO worked ..... strange because it told me that nothing was blocked:

![grafik](https://user-images.githubusercontent.com/3857906/51433811-be2d1680-1c53-11e9-975e-cbe18e78f731.png)

**Comment by simonspa** [comment]
For me, it not only removed the "share link" but also the list of already active shares. Deactivating the adblocker made no difference, but deactivating this app shows everything as it should.

**Comment by supremesyntax** [comment]
Disabling "Social sharing via Diaspora" did the trick for me

**Comment by simonspa** [comment]
The social sharing app seems to cause the content of `linkShareView` and `shareeListView` to not be loaded - the `div`s are there:

### Social sharing diabled:
![image](https://user-images.githubusercontent.com/1677436/51539649-d1f39b00-1e54-11e9-9786-87f479b6e277.png)


### Social sharing enabled:
![image](https://user-images.githubusercontent.com/1677436/51539642-ce601400-1e54-11e9-9bc3-af2287f37cda.png)

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/server/pull/13738

Testing and review are welcome @simonspa @supremesyntax @Huster-at-github @herrmannsdorfer @e-alfred
