### ISSUE TITLE
Share using Mail app or Rainloop (Round Cube etc.)

### ISSUE THREAD

**Issue by beccon4** [nextcloud/socialsharing#30]
The current version requires the mailto to be set up to the correct mailer - which isn't always the case when the user is at another terminal.

On the other hand it would be nice to be able to send a fully fledged email with all the formal bells and whistles containing the link.

So it would be nice to call the Mail app directly- or even better a preset one e.g. RainLoop (which my clients still prefer over the default one)

**Comment by juliushaertl** [comment]
This is something that should be implemented in the apps themselves I think. Please open an issue at the apps repos.
