### ISSUE TITLE
Unable to share / unshare content (NC 15)

### ISSUE THREAD

**Issue by daniel-wtd** [nextcloud/socialsharing#33]
Hey folks,

today I was facing the situation that I am not able to use any of the social sharing apps anymore.
In the sharing dialog it is not visible, that something is share nor editable.

I don't know if this is a bug in displaying the "3 dots" or an issue in the apps or with some settings of mine. I also had a look at the demo and it seems to work over there.

There is also a "share link" button, which is not present for me.

After disabling and removing the apps the button is back.

Would be awesome, if you can have a look.

**Comment by caguiar** [comment]
I enabled email app only and had same issue.
Had to disable app to be able to get the "share link" back.

**Comment by relaire** [comment]
Hi, i va the same problem, witth nextcloud 15.0.2 and socialsharing 1.0.5

**Comment by Linuxfabrik** [comment]
+1, same problem (nc 15.0.2, socialsharing 1.0.5) here, with the same solution (deactivating all the 'social sharing via *' apps)

**Comment by floppy007** [comment]
+1 same problem (nc 15.0.2, facebook socialsharing 1.0.4)
**App activate**
![app enabled](https://user-images.githubusercontent.com/47177775/51978663-08e83300-248b-11e9-9701-b312c9bb1faf.png)
**App disabled**
![app disabled](https://user-images.githubusercontent.com/47177775/51978675-13a2c800-248b-11e9-8514-f98e3adc723b.png)

**Comment by NettoHikari** [comment]
+1

**Comment by PpaiSanchez** [comment]
Same

**Comment by johappel** [comment]
same

**Comment by NiklasOlofsson** [comment]
Same here and it's true for all the social sharing apps.

**Comment by NiklasOlofsson** [comment]
This now works as it should after upgrading to the new 15.0.4.

**Comment by daniel-wtd** [comment]
Seems to be fixed in 15.0.4. Close from my side.

**Comment by relaire** [comment]
That's work for me with 15.0.4. Close for me
