### ISSUE TITLE
Feedback on pull request

### ISSUE THREAD

**Issue by pfmephisto** [nextcloud/socialsharing#43]
A while back I was missing the feature of being able to share links through Telegram.
I took it upon myself to implement that functionality by adapting one of the existing plugins and thought I'd share my work through a pull request #40. 
So far I have not gotten any feedback on why it's not being merged. If it's due to a lack of interest I can accept that, but if me making some more changes will make the process easier I'd be happy to do that.

**Comment by rullzer** [comment]
@pfmephisto sorry for that.
Please do the signoff. I'm fine to merge it here,

**Comment by pfmephisto** [comment]
@rullzer thanks, I did the sign off.
