### ISSUE TITLE
Sharing via email causes internal server error when using Nextcloud Mail app

### ISSUE THREAD

**Issue by villenvie** [nextcloud/socialsharing#47]
Hi,

When I try to use the "Share via e-mail" feature to share a link using the Nextcloud Mail app, I encounter an internal server error.

There is 2 errors in the log : 
[index] Error: Exception: urlencode() expects parameter 1 to be string, null given at <<closure>>

0. /home/clients/*******/sites/cloud.*******.org/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\PageController {}, "compose")
1. /home/clients/*******/sites/cloud.*******.org/lib/private/Route/Router.php line 309
   OC\AppFramework\App::main("OCA\\Mail\\Controller\\PageController", "compose", OC\AppFramework\ ... {}, {_route: "mail.page.compose"})
2. /home/clients/*******/sites/cloud.*******.org/lib/base.php line 1008
   OC\Route\Router->match("/apps/mail/compose")
3. /home/clients/*******/sites/cloud.*******.org/index.php line 37
   OC::handleRequest()

GET /index.php/apps/mail/compose?uri=mailto%3A%3Fsubject%3DI%20shared%20a%20file%20with%20you%26body%3Dhttps%3A%2F%2Fcloud.*******.org%2Findex.php%2Fs%2FwGPrkr2e2oNo36L
from 62.64.60.60 by charles.dupont at 2021-02-25T17:42:44+00:00

[PHP] Error: Error: Undefined index: path at /home/clients/*******/sites/cloud.*******.org/apps/mail/lib/Controller/PageController.php#212 at <<closure>>

0. /home/clients/*******/sites/cloud.*******.org/apps/mail/lib/Controller/PageController.php line 212
   OC\Log\ErrorHandler::onError(8, "Undefined index: path", "/home/clients/f ... p", 212, {uri: "mailto:?s ... }})
1. /home/clients/*******/sites/cloud.*******.org/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Mail\Controller\PageController->compose("mailto:?subject ... L")
2. /home/clients/*******/sites/cloud.*******.org/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Controller\PageController {}, "compose")
3. /home/clients/*******/sites/cloud.*******.org/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\PageController {}, "compose")
4. /home/clients/*******/sites/cloud.*******.org/lib/private/Route/Router.php line 309
   OC\AppFramework\App::main("OCA\\Mail\\Controller\\PageController", "compose", OC\AppFramework\ ... {}, {_route: "mail.page.compose"})
5. /home/clients/*******/sites/cloud.*******.org/lib/base.php line 1008
   OC\Route\Router->match("/apps/mail/compose")
6. /home/clients/*******/sites/cloud.*******.org/index.php line 37
   OC::handleRequest()

GET /index.php/apps/mail/compose?uri=mailto%3A%3Fsubject%3DI%20shared%20a%20file%20with%20you%26body%3Dhttps%3A%2F%2Fcloud.*******.org%2Findex.php%2Fs%2FwGPrkr2e2oNo36L
from 62.64.60.60 by charles.dupont at 2021-02-25T17:42:44+00:00

**Comment by acsfer** [comment]
Is this still valid on recent versions?

**Comment by skjnldsv** [comment]
To be reported on the mail repository
