### ISSUE TITLE
Enable translation

### ISSUE THREAD

**Issue by schiessle** [nextcloud/socialsharing#6]
might be nice to enable translation so that the share messages are in the preferred language of the user

**Comment by LukasReschke** [comment]
Yeah. Makes sense, @MorrisJobke is that possible. Or did we fuck up here with not having them in a single repo? 😄

**Comment by MorrisJobke** [comment]
> Or did we fuck up here with not having them in a single repo? 😄

Needs a bit more logic I think or we have not all in one commit. I would go for now for the easy approach "1 commit per subfolder"

**Comment by MorrisJobke** [comment]
You are heroes .... there are not strings that could be translated 🙈 

Maybe add them for the email app - the subject is english ;)

**Comment by MorrisJobke** [comment]
But it should™ work now.
