### ISSUE TITLE
Release telegram 2.5.0

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/socialsharing#63]
Hey @pfmephisto, it seems you're the only one with the keys of the `socialsharing_telegram` app.
Do you want to transfer it to us so we can take over the maintenance and release alongside the other ones?

If not, could you release 2.5.0?

You can contact me at john@nextcloud.com if you want to share your app key!
Cheers :v:

**Comment by skjnldsv** [comment]
The release is already done here: https://github.com/nextcloud-releases/socialsharing/releases/tag/v2.5.0
You can upload the new version in https://apps.nextcloud.com/developer/apps/releases/new

- You have to download the tar.gz
- Generate the signature with your appkey as mentioned in the [appstore upload page](https://apps.nextcloud.com/developer/apps/releases/new
)
- Upload the release using the hosted tar.gz file

**Comment by pfmephisto** [comment]
I'm actually not sure if I can find my key. It has been so long and with a couple of job and laptop changes in between I think I might have lost it. I am looking through my back ups but otherwise, is it the easiest if I just release my claim to the app and you re-register it?

**Comment by skjnldsv** [comment]
If you're k with that, yes, I can regenerate and take over, sure! :)

**Comment by pfmephisto** [comment]
Great :) I have unlocked it on the "Transfer Apps" page.
If I understand correctly you should be able to just register it again, right?

**Comment by skjnldsv** [comment]
Yep, will see with our sysadmin team! Thank you :)
