### ISSUE TITLE
Small Bug: app.php is deprecated error message

### ISSUE THREAD

**Issue by yupthatguy** [nextcloud/socialsharing#64]
Hey there,

Just doing some maintenance and trying to clear my error log.   Your app throws a app.php deprecation error:

> {"reqId":"Yp5hpCiyfiKpNVlxG1xtqAAAAx4","level":0,"time":"June 06, 2022 20:20:52","remoteAddr":"192.168.61.1","user":"fathertimetest","app":"socialsharing_email","method":"GET","url":"/ocs/v2.php/core/navigation/apps?format=json","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36","version":"24.0.1.1"}

I am on NC24, Ubuntu 20.04, using php7.4-fpm

**Comment by marcelklehr** [comment]
Fixed
