### ISSUE TITLE
Add support for Nextcloud 25 and above

### ISSUE THREAD

**Issue by estebandido81** [nextcloud/socialsharing#68]
Hello,

Nextcloud 25 is out, please release new versions of the app to the App Store.

**Comment by NotReallyNotNotMe** [comment]
No icon for Social Sharing - installed but can not see it. Nextcloud Ver. 25.

**Comment by daffydock** [comment]
It is unfortunate.

**Comment by KlausHuber** [comment]
Any news on that? Nextcloud 25 is already out for a while :(
Or anybody here who's using the plugin successfully on Nextcloud 25?

**Comment by andyxheli** [comment]
Still waiting on the update.

**Comment by skjnldsv** [comment]
You can force enable the app and it works fine here! :)
