### ISSUE TITLE
The releases are not up-to-date with the tags

### ISSUE THREAD

**Issue by SimJoSt** [nextcloud/socialsharing#71]
The [releases](https://github.com/nextcloud/socialsharing/releases) don't contain all releases from the [tags](https://github.com/nextcloud/socialsharing/tags).

And it also doesn't adhere to:
- https://nextcloudappstore.readthedocs.io/en/latest/developer.html?highlight=changelog#changelog
- https://keepachangelog.com/

So the "Changelog" tab in the Nextcloud admin app interface stays empty when opening the details of the app.

**Comment by marcelklehr** [comment]
Releases are nowadays created in the nextcloud-releases org: https://github.com/nextcloud-releases/socialsharing/releases

I'll add a CHANGELOG , thanks for the heads up :)
